server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: users
            uri: 'http://localhost:8081'
            predicates:
              - Path=/api/user/**
          - id: microservice-suscripcion
            uri: 'http://localhost:8082'
            predicates:
              - Path=/api/subscription/**
          - id: courses
            uri: 'http://localhost:8083'
            predicates:
              - Path=/api/course/**
eureka:
  client:
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0